# Generated by Django 5.1.1 on 2024-10-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.member')),
            ],
        ),
    ]
